# Generated by Django 6.0.5 on 2026-05-13 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('landing_path', models.CharField(blank=True, max_length=500)),
                ('referrer_domain', models.CharField(blank=True, max_length=253)),
                ('device_class', models.CharField(blank=True, max_length=20)),
                ('browser_family', models.CharField(blank=True, max_length=50)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('human_likelihood', models.CharField(default='unknown', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='BlockManifestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('block_version_id', models.CharField(blank=True, max_length=300)),
                ('content_hash', models.CharField(blank=True, max_length=80)),
                ('position_hash', models.CharField(blank=True, max_length=80)),
                ('page_path', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('heading_path', models.CharField(blank=True, max_length=1000)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('concept', models.CharField(blank=True, max_length=100)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(blank=True, max_length=500)),
                ('parent_block_id', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTransitionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('from_page_path', models.CharField(max_length=500)),
                ('to_page_path', models.CharField(max_length=500)),
                ('from_block_id', models.CharField(blank=True, max_length=200)),
                ('to_block_id', models.CharField(blank=True, max_length=200)),
                ('from_topic', models.CharField(blank=True, max_length=100)),
                ('to_topic', models.CharField(blank=True, max_length=100)),
                ('transition_count', models.PositiveIntegerField(default=0)),
                ('unique_sessions', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyBlockSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('block_id', models.CharField(db_index=True, max_length=200)),
                ('block_version_id', models.CharField(blank=True, max_length=300)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('concept', models.CharField(blank=True, max_length=100)),
                ('unique_sessions', models.PositiveIntegerField(default=0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('total_visible_seconds', models.FloatField(default=0.0)),
                ('median_visible_seconds', models.FloatField(null=True)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('downloads_after_exposure', models.PositiveIntegerField(default=0)),
                ('external_clicks_after_exposure', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'block_id', 'block_version_id')},
            },
        ),
        migrations.CreateModel(
            name='DailyTopicSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('unique_sessions', models.PositiveIntegerField(default=0)),
                ('total_visible_seconds', models.FloatField(default=0.0)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp_client', models.DateTimeField(blank=True, null=True)),
                ('event_sequence', models.PositiveIntegerField()),
                ('page_path', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('block_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('block_version_id', models.CharField(blank=True, db_index=True, max_length=300)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=80)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=100)),
                ('concept', models.CharField(blank=True, db_index=True, max_length=100)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('previous_page_path', models.CharField(blank=True, max_length=500)),
                ('previous_block_id', models.CharField(blank=True, max_length=200)),
                ('seconds_since_previous_event', models.FloatField(blank=True, null=True)),
                ('seconds_visible', models.FloatField(blank=True, null=True)),
                ('intersection_ratio', models.FloatField(blank=True, null=True)),
                ('scroll_depth', models.FloatField(blank=True, null=True)),
                ('target_path', models.CharField(blank=True, max_length=500)),
                ('target_domain', models.CharField(blank=True, max_length=253)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='concept_analytics.analyticssession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'event_sequence'], name='concept_ana_session_a5188d_idx'), models.Index(fields=['received_at'], name='concept_ana_receive_a146ec_idx')],
            },
        ),
    ]
