# Generated by Django 6.0.5 on 2026-05-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concept_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsevent',
            options={'permissions': [('view_dashboard', 'Can view concept analytics dashboard')]},
        ),
    ]
