# Generated by Django 6.0.5 on 2026-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept_analytics', '0003_manifestsyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssession',
            name='report_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='manifestsyncstate',
            name='report_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='manifestsyncstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
